import "./globals.css";
import Head from "next/head";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Qasim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title as React.ReactNode}</title>
        <link rel="icon" href="/resources/assets/favicon.png" />
        <meta
          name="description"
          content={metadata.description ?? "Default description"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="keywords"
          content="Software Engineer, Developer, Entrepreneur"
        />
        <meta
          property="og:title"
          content="Qasim | Building web-driven enterprises."
        />
        <meta property="og:type" content="website" />
        <meta
          property="og:image:secure_url"
          content="https://qasim.fyi/resources/images/portfolio-preview.png"
        />
        <meta property="og:url" content="https://qasim.fyi" />
        <meta property="og:description" content="" />
        <meta
          property="og:image"
          content="https://qasim.fyi/resources/images/og.png"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="qasim.fyi" />
        <meta property="twitter:url" content="https://qasim.fyi" />
        <meta
          name="twitter:title"
          content="Qasim | Building web-driven enterprises."
        />
        <meta name="twitter:description" content="" />
        <meta
          name="twitter:image"
          content="https://qasim.fyi/resources/images/og.png"
        />
      </head>
      <body className={inter.className}>
        {children} <Analytics />
      </body>
    </html>
  );
}
