import React from "react";
import Image from "next/image";
import Link from "next/link";

const FeaturedProjects: React.FC = () => {
  const featuredProjects = [
    {
      url: "/resources/assets/aifitnessproject.png",
      link: "https://github.com/theqasim/aifitness",
      title: "AIFitness",
      description: "A web application that initially generates a customized workout plan based on user inputs such as gender, fitness goals, and target muscle groups. After creating the plan, the app provides an interactive AI coach through a chatbot interface to guide users in achieving their workout goals.",
      smallText: "NextJS  TypeScript  Tailwind CSS",
      githubUrl: "https://github.com/theqasim/aifitness",
      newTabUrl: "https://newtab1.com",
    },
    {
      url: "/resources/assets/aicontentdetectionproject.png",
      link: "https://youtu.be/5bYfRT6PBk8",
      title: "AI Content Detector",
      description: "An advanced AI content detection tool utilizes sophisticated machine learning algorithms to accurately gauge the likelihood that a given piece of content is generated by artificial intelligence. It provides a unique percentage score to indicate the content's level of authenticity.",
      smallText: "NextJS  TypeScript  Tailwind CSS",
      githubUrl: "https://github.com/project2",
      newTabUrl: "https://youtu.be/5bYfRT6PBk8",
    },
    {
      url: "/resources/assets/aivoiceassistantproject.png",
      link: "https://github.com/theqasim/AI-Voice",
      title: "AI Voice Assistant",
      description: "An AI voice assistant powered by the ChatGPT API, capable of natural language recognition and task execution. It interfaces with other apps and continually improves its voice and text responses through machine learning, providing an intuitive, personalized experience.",
      smallText: "HTML JavaScript CSS",
      githubUrl: "https://github.com/theqasim/AI-Voice",
      newTabUrl: "https://youtu.be/PCfmGgQuee8",
    },
  ];

  return (
    <div className="flex flex-col space-y-12 justify-center items-center mb-14 mt-8">
      <h1 className="text-4xl font-bold  self-start">
        <a className="text-black  transition-all duration-500 ease-in-out border-b-4 border-transparent hover:border-black font-maison">
          Featured Projects
        </a>
      </h1>
      {featuredProjects.map((item, index) => (
        <div className="relative w-[550px] h-[320px] transition ease-in-out delay-120 hover:-translate-y-2 duration-300 relative drop-shadow-lg hover:drop-shadow-2xl" key={index}>
          <Image
            src={item.url}
            alt={item.title}
            width={550}
            height={380}
            className="object-cover"
          />
          <div className="absolute inset-0 w-4/5 h-full flex flex-col justify-start items-start p-4 ml-6 mt-12">
            <h3 className="text-white font-bold text-lg mb-5 font-maison">
              <a href={item.link} target="_blank" rel="noopener noreferrer" className="cursor-pointer underline-effect">
                {item.title}
              </a>
            </h3>
            <p className="text-white text-sm mb-8">{item.description}</p>
            <small className="text-white text-xs font-mono">{item.smallText}</small>
            <div className="flex space-x-4 mt-3">
              <a href={item.githubUrl} target="_blank" rel="noopener noreferrer" className="cursor-pointer">
                <Image src="/resources/assets/github.svg" alt="Github" width={32} height={32} />
              </a>
              <a href={item.newTabUrl} target="_blank" rel="noopener noreferrer" className="cursor-pointer">
                <Image className="" src="/resources/assets/newtabwhitee.svg" alt="New Tab" width={32} height={32} />
              </a>
            </div>
          </div>
        </div>
      ))}
    </div>
  );






};

export default FeaturedProjects;
