import React from "react";
import Image from "next/image";

const FeaturedProjects: React.FC = () => {
  const featuredProjects = [
    {
      url: "/resources/assets/aifitnessproject.png",
      link: "https://github.com/theqasim/aifitness",
      title: "AIFitness",
      description:
        "A web application that initially generates a customized workout plan based on user inputs such as gender, fitness goals, and target muscle groups. After creating the plan, the app provides an interactive AI coach through a chatbot interface to guide users in achieving their workout goals.",
      smallText: "NextJS  TypeScript  Tailwind CSS",
      githubUrl: "https://github.com/theqasim/aifitness",
      newTabUrl: "https://aifitness-eight.vercel.app",
    },
    {
      url: "/resources/assets/aicontentdetectionproject.png",
      link: "https://github.com/theqasim/AI-Detect",
      title: "AI Content Detector",
      description:
        "An advanced AI content detection tool utilizes sophisticated machine learning algorithms to accurately gauge the likelihood that a given piece of content is generated by artificial intelligence. It provides a unique percentage score to indicate the content's level of authenticity.",
      smallText: "NextJS  TypeScript  Tailwind CSS",
      githubUrl: "https://github.com/theqasim/AI-Detect",
      newTabUrl: "https://youtu.be/5bYfRT6PBk8",
    },
    {
      url: "/resources/assets/aivoiceassistantproject.png",
      link: "https://github.com/theqasim/AI-Voice",
      title: "AI Voice Assistant",
      description:
        "An AI voice assistant powered by the ChatGPT API, capable of natural language recognition and task execution. It interfaces with other apps and continually improves its voice and text responses through machine learning, providing an intuitive, personalized experience.",
      smallText: "HTML JavaScript CSS",
      githubUrl: "https://github.com/theqasim/AI-Voice",
      newTabUrl: "https://youtu.be/PCfmGgQuee8",
    },
  ];

  return (
    <div className="flex flex-col space-y-12 justify-center items-center mb-14 mt-8">
      <h1 className="text-4xl font-bold self-start">
        <a className="text-black transition-all duration-500 ease-in-out border-b-4 border-transparent hover:border-black font-maison">
          Featured Projects
        </a>
      </h1>
      {featuredProjects.map((item, index) => (
        <div
          className="relative w-[550px] h-[320px] transition ease-in-out delay-120 hover:-translate-y-2 duration-300 relative drop-shadow-lg hover:drop-shadow-2xl"
          key={index}
        >
          <Image
            src={item.url}
            alt={item.title}
            width={550}
            height={380}
            className="object-cover"
          />
          <div className="absolute inset-0 w-4/5 h-full flex flex-col justify-start items-start p-4 ml-6 mt-12">
            <h3 className="text-white font-bold text-lg mb-5 font-maison">
              <a
                href={item.link}
                target="_blank"
                rel="noopener noreferrer"
                className="cursor-pointer underline-effect"
              >
                {item.title}
              </a>
            </h3>
            <p className="text-white text-sm mb-8">{item.description}</p>
            <small className="text-white text-xs font-mono">
              {item.smallText}
            </small>
            <div className="flex space-x-4 mt-3">
              <a
                href={item.githubUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="cursor-pointer hover:fill-current hover:text-blue-500"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                  fill="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
              </a>
              <a
                href={item.newTabUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="cursor-pointer hover:fill-current hover:text-blue-500"
              >
                <svg
                  className="w-6 h-6"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  viewBox="0 0 18 18"
                >
                  <path d="M17 0h-5.768a1 1 0 1 0 0 2h3.354L8.4 8.182A1.003 1.003 0 1 0 9.818 9.6L16 3.414v3.354a1 1 0 0 0 2 0V1a1 1 0 0 0-1-1Z" />
                  <path d="m14.258 7.985-3.025 3.025A3 3 0 1 1 6.99 6.768l3.026-3.026A3.01 3.01 0 0 1 8.411 2H2.167A2.169 2.169 0 0 0 0 4.167v11.666A2.169 2.169 0 0 0 2.167 18h11.666A2.169 2.169 0 0 0 16 15.833V9.589a3.011 3.011 0 0 1-1.742-1.604Z" />
                </svg>{" "}
              </a>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default FeaturedProjects;
